=== tjaartvdwalt/graduate-advisor/xml/Courses.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="descriptions">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="course">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subject" type="xs:string"/>
                            <xs:element name="course_number" type="xs:integer"/>
                            <xs:element name="course_name" type="xs:string"/>
                            <xs:element name="credit" type="xs:string"/>
                            <xs:element name="course_description" type="xs:string"/>
                            <xs:element maxOccurs="1" minOccurs="0" name="can_select_multiple"
                                type="xs:boolean"/>
                            <xs:element maxOccurs="1" minOccurs="0" name="prerequisite"
                                nillable="false" form="qualified">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="1" minOccurs="0" name="or_choice">
                                            <xs:complexType mixed="false">
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="and_required" nillable="false">
                                                  <xs:simpleType>
                                                  <xs:list itemType="xs:string"/>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="additional_preq"
                                            nillable="false" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tjaartvdwalt/graduate-advisor/xml/Courses.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://comp.umsl.edu/~xml_data/Courses.xsd">
<course>
	<subject>CMP SCI</subject>
   <course_number>1010</course_number>
	<course_name>Introduction To Computers And The Internet</course_name>
	<credit>3</credit>
	<course_description>Covers basic concepts and components of a PC: survey of popular applications including e-mail, word processors, spreadsheets,  overview of the Internet, popular browsers, World Wide Web, search engines, multimedia, web pages, security, and privacy. Credit not granted for both CMP SCI 1010 and INF SYS 1800.</course_description>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>1011</course_number>
	<course_name>Introduction to the Internet and World Wide Web	</course_name>
	<credit>3</credit>
	<course_description>Intended for any student wishing to utilize the Internet and World Wide Web more effectively. Topics include networking basics, the Internet and World Wide Web, browsers, search engines, Web Services, utilities, tools, online privacy and security. Students will learn to develop a personal web page using skills acquired in the course</course_description>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>1012</course_number>
   <course_name>Learning to Program Using Virtual Worlds	</course_name>
	<credit>3</credit>
	<course_description>Introduces modern programming principles without requiring the knowledge of a traditional programming language. Instead, this course utilizes a novel graphical approach that enables the student to create, populate, and manipulate virtual 3-dimensional worlds which resemble video games. The development of these worlds allows students to gain direct experience and skills in using computers to solve problems. Students will create worlds of varying complexity.</course_description>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>1250</course_number>
   <course_name>Introduction to Computing</course_name>
	<credit>3</credit>
	<course_description>Provides an introduction to the concepts of computation, problem solving, and computer systems, Covers fundamental programming constructs, basic data types, and modularization using a modern high level language. Problem solving skills are developed through a progression of programming projects.</course_description>
	<prerequisite>
	   <or_choice>
         <and_required>MATH 1030</and_required>
	      <and_required>MATH 1100</and_required>
	      <and_required>MATH 1800</and_required>
	   </or_choice>
	   <additional_preq>MATH 1030 with B- or better</additional_preq>
	</prerequisite>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>2250</course_number>
	<course_name>Programming and Data Structures</course_name>
	<credit>3</credit>
	<course_description>A continuation of CMP SCI 1250. Discusses properties and implementation of abstract data types such as lists, trees, stacks and queues. Introduces procedural and class abstraction, basic program architecture, use of interfaces, modular programming, and file processing.</course_description>
   <prerequisite>
      <or_choice>
         <and_required>CMP SCI 1250</and_required>
      </or_choice>
    </prerequisite>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>2261</course_number>
	<course_name>Object-Oriented Programming</course_name>
	<credit>3</credit>
	<course_description>Introduces object-oriented concepts, terminology, and notation (UML) using Java. Covers encapsulation, classes, objects, inheritance, and the use of class libraries. Additional topics may include graphical user interfaces, applets, and related tools and technologies.</course_description>
	<prerequisite>
	   <or_choice>
	      <and_required>CMP SCI 2250</and_required>
      </or_choice>
	</prerequisite>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>2700</course_number>
	<course_name>Computer Architecture and Organization</course_name>
	<credit>3</credit>
	<course_description>Introduces details of computer systems from architectural and organizational points of view. Covers data representation, basic digital logic circuits, memory types and hierarchies, I/O and storage devices, CPU architectures such as RISC, CISC, parallel, and multi-core.</course_description>
	<prerequisite>
	   <or_choice>
         <and_required>CMP SCI 2250</and_required>
	   </or_choice>
	</prerequisite>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>2750</course_number>
	<course_name>System Programming and Tools</course_name>
	<credit>3</credit>
	<course_description>Covers systems programming, scripting, libraries, utilities, and development tools. Additional programming topics include piping, binary files, exception handling, command-line arguments and symbolic debugging. This course also explores tools available in the Unix/Linus environments.</course_description>
	<prerequisite>
	   <or_choice>
	      <and_required>CMP SCI 2250</and_required>
		</or_choice>
	</prerequisite>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>3010</course_number>
   <course_name>Web Programming</course_name>
	<credit>3</credit>
	<course_description>Provides a survey of current Web technologies including markup languages (such as HTML/XHTML, CSS, XML), client side languages (such as JavaScript), server side languages (such as PERL, PHP), and Web protocols. This course requires client-server computing projects.</course_description>
	<prerequisite>
	   <or_choice>
	      <and_required>CMP SCI 2250</and_required>
		</or_choice>
	</prerequisite>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>3130</course_number>
	<course_name>Design and Analysis of Algorithms</course_name>
	<credit>3</credit>
	<course_description>Addresses the design and analysis of fundamental algorithms in computer science. Studies basic sorting algorithms priority queues, order statistics, search trees, and hash tables. Analysis techniques may involve time and space complexity analysis of both iterative and recursive algorithms, analysis of algorithm correctness, and amortized complexity analysis. Additional topics may include data compression, string manipulation, greedy algorithms, dynamic programming, and graph traversal.</course_description>
	<prerequisite>
	   <or_choice>
	      <and_required>CMP SCI 2250,MATH 1320,MATH 2450,MATH 3000</and_required>
	   </or_choice>
	</prerequisite>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>3710</course_number>
	<course_name>Assembly Language Programming</course_name>
	<credit>3</credit>
	<course_description>Explore machine architecture concepts and principles through a study of assembly language programming. Topics covered include integer and floating point arithmetic, procedures, conditional processing, strings, macros, and interfaces to high level languages. Programming projects using a commercially available assembly language will be required.</course_description>
	<prerequisite>
	   <or_choice>
	      <and_required>CMP SCI 2700</and_required>
	   </or_choice>
	</prerequisite>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>4010</course_number>
   <course_name>Advanced Web Development with Java</course_name>
   <credit>3</credit>
	<course_description>Covers more advanced Java topics, along with related concepts and technologies for Web development. Topics may include database connectivity, multithreading, security, networking, MVC pattern, testing and source control for Java applications, and server-side topics such as servlets and web servers.</course_description>
	<prerequisite>
	   <or_choice>   
	      <and_required>CMP SCI 2261,CMP SCI 3010</and_required>
	   </or_choice>
	</prerequisite>
</course>
<course>
	<subject>CMP SCI</subject>
   <course_number>4030</course_number>
	<course_name>Introduction to Intelligent Web</course_name>
	<credit>3</credit>
	<course_description>Covers the application of artificial intelligence and other modern techniques to help construct, navigate, and experience the Web. Topics may include retrieval models, classification, mining, association, topology, and indexing algorithms such as PageRank and HITS. Credit cannot be earned for both CMP SCI 4030 and CMP SCI 5030.</course_description>
	<prerequisite>
	   <or_choice>
	      <and_required>CMP SCI 2261,CMP SCI 2750,CMP SCI 3010,CMP SCI 3130</and_required>
	   </or_choice>
	</prerequisite>
</course>
<course>
   <subject>CMP SCI</subject>
   <course_number>4040</course_number>
   <course_name>Electronic Commerce Protocols</course_name>
   <credit>3</credit>
   <course_description>Provides a technical introduction to electronic commerce over the Internet, examining topics such as electronic data interchange, digital currency, and electronic catalogs. The course discusses technical issues such as telecommunications infrastructure, data warehousing, software agents, and storage retrieval of multimedia information. Other topics may include cryptographic techniques as applicable to web-site development, management of data in a secure manner, authentication and confidentiality, different levels of security (transaction, network, and protocol), and digital signatures.</course_description>
   <prerequisite>
      <or_choice>
         <and_required>CMP SCI 2750, MATH 2450</and_required>
      </or_choice>
   </prerequisite>
</course>
<course>
   <subject>CMP SCI</subject>
   <course_number>4050</course_number>
   <course_name>User Interface Development</course_name>
   <credit>3</credit>
