=== tjaartvdwalt/graduate-advisor/xml/Rotation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Rotations">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="rotation_year" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="year" maxOccurs="1" minOccurs="1" nillable="false"
                                type="xs:integer"/>
                            <xs:element maxOccurs="unbounded" name="course" minOccurs="1"
                                nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="subject" type="xs:string" maxOccurs="1"
                                            minOccurs="1" nillable="false"/>
                                        <xs:element name="course_number" type="xs:string"
                                            maxOccurs="1" minOccurs="1" nillable="false"/>
                                        <xs:element name="course_name" type="xs:string"
                                            maxOccurs="1" minOccurs="1" nillable="false"/>
                                        <xs:element maxOccurs="2" minOccurs="2" name="rotation_term"
                                            nillable="false">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="term" nillable="false"
                                                  type="xs:string" maxOccurs="1" minOccurs="1"/>
                                                  <xs:element maxOccurs="1" minOccurs="1"
                                                  name="time_code" nillable="true">
                                                  <xs:simpleType>
                                                  <xs:list itemType="xs:string"/>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tjaartvdwalt/graduate-advisor/sandbox/test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Rotations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://comp.umsl.edu/~xml_data/Rotation.xsd">
  <rotation_year>
    <year>2013</year>
    <course>
      <subject>CMP SCI</subject>
      <course_number>1250</course_number>
      <course_name>Introduction to Computing</course_name>
      <rotation_term>
        <term>Spring</term>
        <time_code></time_code>
      </rotation_term>
      <rotation_term>
        <term>Fall</term>
        <time_code>D,E</time_code>
      </rotation_term>
    </course>
    <course>
      <subject>CMP SCI</subject>
      <course_number>2250</course_number>
      <course_name>Programming and Data Structures</course_name>
      <rotation_term>
        <term>Spring</term>
        <time_code></time_code>
      </rotation_term>
      <rotation_term>
        <term>Fall</term>
        <time_code>D</time_code>
      </rotation_term>
    </course>
  </rotation_year>
</Rotations>
